### ISSUE TITLE
验证时出现异常，求解决

### ISSUE THREAD

**Issue by Mooshed88-a** [MrXiaoM/PremiumVerify#3]
版本：1.20.4paper
[21:25:39 WARN]: [PremiumVerify] 玩家 Mooshed88 进行正版验证时出现一个异常
[21:25:39 WARN]: [PremiumVerify] java.lang.NoClassDefFoundError: Could not initialize class top.mrxiaom.premiumverify.utils.jsonwebtoken.Jwts$SIG
        at PremiumVerify-1.0.2.jar//top.mrxiaom.premiumverify.utils.auth.util.CryptUtil.getSignatureHeader(CryptUtil.java:127)
        at PremiumVerify-1.0.2.jar//top.mrxiaom.premiumverify.utils.auth.step.xbl.StepXblDeviceToken.execute(StepXblDeviceToken.java:78)
        at PremiumVerify-1.0.2.jar//top.mrxiaom.premiumverify.utils.auth.step.xbl.StepXblDeviceToken.execute(StepXblDeviceToken.java:41)
        at PremiumVerify-1.0.2.jar//top.mrxiaom.premiumverify.utils.auth.step.AbstractStep.getFromInput(AbstractStep.java:77)
        at PremiumVerify-1.0.2.jar//top.mrxiaom.premiumverify.utils.auth.step.BiMergeStep.getFromInput(BiMergeStep.java:54)
        at PremiumVerify-1.0.2.jar//top.mrxiaom.premiumverify.utils.auth.step.BiMergeStep.getFromInput(BiMergeStep.java:23)
        at PremiumVerify-1.0.2.jar//top.mrxiaom.premiumverify.utils.auth.step.AbstractStep.getFromInput(AbstractStep.java:77)
        at PremiumVerify-1.0.2.jar//top.mrxiaom.premiumverify.utils.auth.step.AbstractStep.getFromInput(AbstractStep.java:77)
        at PremiumVerify-1.0.2.jar//top.mrxiaom.premiumverify.utils.auth.step.AbstractStep.getFromInput(AbstractStep.java:77)
        at PremiumVerify-1.0.2.jar//top.mrxiaom.premiumverify.utils.auth.step.SameInputBiMergeStep.getFromInput(SameInputBiMergeStep.java:54)
        at PremiumVerify-1.0.2.jar//top.mrxiaom.premiumverify.Request.run(Request.java:57)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: zip file closed [in thread "Thread-92"]
        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:838)
        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:337)
        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:517)
        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:472)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at PremiumVerify-1.0.2.jar//top.mrxiaom.premiumverify.utils.jsonwebtoken.lang.Classes$ExceptionIgnoringAccessor.loadClass(Classes.java:377)
        at PremiumVerify-1.0.2.jar//top.mrxiaom.premiumverify.utils.jsonwebtoken.lang.Classes.forName(Classes.java:72)
        at PremiumVerify-1.0.2.jar//top.mrxiaom.premiumverify.utils.jsonwebtoken.lang.Classes.newInstance(Classes.java:173)
        at PremiumVerify-1.0.2.jar//top.mrxiaom.premiumverify.utils.jsonwebtoken.Jwts$SIG.<clinit>(Jwts.java:174)
        ... 12 more

**Comment by MrXiaoM** [comment]
```
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: zip file closed
```
压缩包损坏，或者是热加载异常，建议重新下载
